# Generated by Django 5.1.4 on 2025-01-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0004_rename_name_users_fullname_remove_users_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
