# Generated by Django 5.1.4 on 2025-01-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_rename_user_id_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='user_id',
        ),
    ]
